### ISSUE TITLE
The SDK code examples are missing

### ISSUE THREAD

**Issue by imjoey** [oVirt/ovirt-engine-sdk#59]
I find that the SDK code examples are no longer in the repository. May I ask why, as the examples are constructive and helpful. The readme file [here](https://github.com/oVirt/ovirt-engine-sdk/blob/91ffc9412a982eab5754edd18bed8eb412e592a3/sdk/README.adoc#more-information) still shows the link of code examples directory.
Thanks.

**Comment by mwperina** [comment]
Originally [oVirt/ovirt-engine-sdk](https://github.com/oVirt/ovirt-engine-sdk) repo contained both generator (written in Java) and generated Python SDK code. In order to simplify the project we split it into 2 repositories as a part of https://github.com/oVirt/ovirt-engine-sdk/pull/48  :

-  [oVirt/ovirt-engine-sdk](https://github.com/oVirt/ovirt-engine-sdk)
  - It contains the generator code and configuration
  - Merging PR with changes into this project will regenerate Python SDK which is automatically merged into [oVirt/python-ovirt-engine-sdk4](https://github.com/oVirt/python-ovirt-engine-sdk4)
- [oVirt/python-ovirt-engine-sdk4](https://github.com/oVirt/python-ovirt-engine-sdk4)
  - It contains Python SDK source codes, documentation and examples
  - Merging a PR into this repo will produce new nightly build of Python SDK RPM package

All existing Python SDK examples can be found at the new location https://github.com/oVirt/python-ovirt-engine-sdk4/tree/main/examples

**Comment by imjoey** [comment]
@mwperina ok, got it. Thank you very much for your reply. I'll lose this issue.
